version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # Assume que o Dockerfile na raiz é para o backend
    ports:
      # A porta do backend exposta, usada pelo https://backend.clayforgestudio.com.br
      # para acessar o container do backend.
      - "3000:3000"
    environment:
      # Suas variáveis de ambiente do backend
      - NODE_ENV=production
      # ...
    restart: always

  frontend:
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile # Usa o Dockerfile que você forneceu para o frontend
    ports:
      # Mapeia a porta 80 do Nginx interno do frontend para a porta 3003 do host.
      # Seu Nginx externo (do host) irá encaminhar o tráfego para esta porta.
      - "3003:80"
    environment:
      # Se você usar VITE_APP_BASE_PATH no vite.config.js para a propriedade 'base',
      # pode definir aqui. Caso contrário, se 'base: /galeriloop/' for fixo no vite.config.js, esta linha não é necessária.
      # - VITE_APP_BASE_PATH=/galeriloop
      # VITE_API_URL já está sendo definido no Dockerfile para o processo de build.
      # Se você quisesse sobrescrever essa variável em tempo de execução, seria aqui,
      # mas para a URL da API absoluta no build, o Dockerfile já resolve.
      NO_OP: "This is a placeholder" # Apenas para mostrar que 'environment' pode estar vazio ou com outras vars
    depends_on:
      - backend # Ainda útil para garantir ordem de inicialização se o backend for acessado por outras formas
    restart: always